spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: password
  jpa:
    show-sql: false
    defer-datasource-initialization: true