spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: password
  jpa:
    show-sql: true
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace